#!/bin/bash

echo "#!/bin/bash" > /usr/bin/tra
echo "sh -c 'xprop -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY \$(printf 0x%x \$((0xffffffff * 85 / 100)
))'" >> /usr/bin/tra
chmod +x /usr/bin/tra
echo "Now run the command tra and click any window. Then ooh and ahh and text me about what you think, Jimmy. :)"
